services:
  candidate-service:
    build: .
    environment:
      PROVIDER_URL: http://provider-simulator:8081
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/payments_db
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - candidate-data:/data

  provider-simulator:
    image: ghcr.io/fintech-dev-lab/internship-provider-simulator:v0.2.0
    environment:
      CALLBACK_URL: http://candidate-service:8080/receipts
    ports:
      - "8081:8081"
    depends_on:
      - candidate-service


  db:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: payments_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d payments_db" ]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  candidate-data:
  pgdata: