"""initial schema

Revision ID: f4543ea2c6b4
Revises: 
Create Date: 2026-07-20 20:20:03.521831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4543ea2c6b4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operations',
    sa.Column('operation_id', sa.String(length=45), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('CREATED', 'PROCESSING', 'COMPLETED', 'REJECTED', name='operationstatus'), nullable=False),
    sa.Column('provider_payment_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('operation_id'),
    sa.UniqueConstraint('provider_payment_id')
    )
    op.create_index('ix_operations_status', 'operations', ['status'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operation_id', sa.String(length=45), nullable=False),
    sa.Column('sequence_no', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('from_status', sa.Enum('CREATED', 'PROCESSING', 'COMPLETED', 'REJECTED', name='operationstatus'), nullable=True),
    sa.Column('to_status', sa.Enum('CREATED', 'PROCESSING', 'COMPLETED', 'REJECTED', name='operationstatus'), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['operation_id'], ['operations.operation_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('operation_id', 'sequence_no')
    )
    op.create_table('send_jobs',
    sa.Column('operation_id', sa.String(length=45), nullable=False),
    sa.Column('state', sa.Enum('PENDING', 'RUNNING', 'WAITING_RETRY', 'DONE', name='sendjobstate'), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['operation_id'], ['operations.operation_id'], ),
    sa.PrimaryKeyConstraint('operation_id')
    )
    op.create_index('ix_send_jobs_state', 'send_jobs', ['state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_send_jobs_state', table_name='send_jobs')
    op.drop_table('send_jobs')
    op.drop_table('events')
    op.drop_index('ix_operations_status', table_name='operations')
    op.drop_table('operations')
    # ### end Alembic commands ###
